# Part 2: DataFrames and Series

In this section, we'll dive deeper into the core data structures of pandas: the **Series** (1D) and the **DataFrame** (2D). We'll also learn how to select specific rows and columns using `loc` and `iloc`.

In [2]:
import pandas as pd

## Python Dictionaries vs. Pandas DataFrames
Before we use pandas, let's look at how we might represent data using standard Python dictionaries. This helps us understand why DataFrames are so powerful.

In [ ]:
person = {
    "first": "Virat",
    "last": "Kohli",
    "email": "virat.kohli@gmail.com"
}

In [3]:
people = {
    "first": ["Virat"],
    "last": ["Kohli"],
    "email": ["virat.kohli@gmail.com"]
}

In [4]:
people = {
    "first": ["Rohit", "Virat", "Jasprit", "Shubman", "Hardik", "Rishabh", "Suryakumar", "Ravindra", "Kuldeep", "Arshdeep", "Axar"],
    "last": ["Sharma", "Kohli", "Bumrah", "Gill", "Pandya", "Pant", "Yadav", "Jadeja", "Yadav", "Singh", "Patel"],
    "email": [
        "rohit.sharma@email.com", 
        "virat.kohli@email.com", 
        "jasprit.bumrah@email.com", 
        "shubman.gill@email.com", 
        "hardik.pandya@email.com", 
        "rishabh.pant@email.com", 
        "suryakumar.yadav@email.com", 
        "ravindra.jadeja@email.com", 
        "kuldeep.yadav@email.com", 
        "arshdeep.singh@email.com", 
        "axar.patel@email.com"
    ]
}

In [5]:
people["email"]

['rohit.sharma@email.com',
 'virat.kohli@email.com',
 'jasprit.bumrah@email.com',
 'shubman.gill@email.com',
 'hardik.pandya@email.com',
 'rishabh.pant@email.com',
 'suryakumar.yadav@email.com',
 'ravindra.jadeja@email.com',
 'kuldeep.yadav@email.com',
 'arshdeep.singh@email.com',
 'axar.patel@email.com']

In [6]:
df = pd.DataFrame(people)

## Creating a DataFrame
We can easily convert a dictionary where values are lists into a pandas DataFrame. Think of the keys as columns and the lists as the data in those columns.

In [7]:
df

         first    last                       email
0        Rohit  Sharma      rohit.sharma@email.com
1        Virat   Kohli       virat.kohli@email.com
2      Jasprit  Bumrah    jasprit.bumrah@email.com
3      Shubman    Gill      shubman.gill@email.com
4       Hardik  Pandya     hardik.pandya@email.com
5      Rishabh    Pant      rishabh.pant@email.com
6   Suryakumar   Yadav  suryakumar.yadav@email.com
7     Ravindra  Jadeja   ravindra.jadeja@email.com
8      Kuldeep   Yadav     kuldeep.yadav@email.com
9     Arshdeep   Singh    arshdeep.singh@email.com
10        Axar   Patel        axar.patel@email.com

In [8]:
type(df)

pandas.DataFrame

In [9]:
df['email']

0         rohit.sharma@email.com
1          virat.kohli@email.com
2       jasprit.bumrah@email.com
3         shubman.gill@email.com
4        hardik.pandya@email.com
5         rishabh.pant@email.com
6     suryakumar.yadav@email.com
7      ravindra.jadeja@email.com
8        kuldeep.yadav@email.com
9       arshdeep.singh@email.com
10          axar.patel@email.com
Name: email, dtype: str

## Accessing Columns
Columns are actually **Series** objects. You can access them using bracket notation (recommended) or dot notation.

In [10]:
type(df['email'])

pandas.Series

In [11]:
df.email

0         rohit.sharma@email.com
1          virat.kohli@email.com
2       jasprit.bumrah@email.com
3         shubman.gill@email.com
4        hardik.pandya@email.com
5         rishabh.pant@email.com
6     suryakumar.yadav@email.com
7      ravindra.jadeja@email.com
8        kuldeep.yadav@email.com
9       arshdeep.singh@email.com
10          axar.patel@email.com
Name: email, dtype: str

In [12]:
df[['last', 'email']]

      last                       email
0   Sharma      rohit.sharma@email.com
1    Kohli       virat.kohli@email.com
2   Bumrah    jasprit.bumrah@email.com
3     Gill      shubman.gill@email.com
4   Pandya     hardik.pandya@email.com
5     Pant      rishabh.pant@email.com
6    Yadav  suryakumar.yadav@email.com
7   Jadeja   ravindra.jadeja@email.com
8    Yadav     kuldeep.yadav@email.com
9    Singh    arshdeep.singh@email.com
10   Patel        axar.patel@email.com

To select multiple columns, pass a **list** of column names inside the brackets. This returns a new DataFrame.

In [14]:
type(df[['last', 'email']])

pandas.DataFrame

In [15]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [16]:
df.iloc[0]

first                     Rohit
last                     Sharma
email    rohit.sharma@email.com
Name: 0, dtype: str

## Selecting Rows: iloc vs. loc
Pandas provides two main ways to select rows:
1. `iloc`: Integer-location based indexing (using 0-based positions).
2. `loc`: Label-based indexing (using names/labels).

In [17]:
type(df.iloc[0])

pandas.Series

In [18]:
df.iloc[[0,1]]

   first    last                   email
0  Rohit  Sharma  rohit.sharma@email.com
1  Virat   Kohli   virat.kohli@email.com

In [19]:
df.iloc[[0,1], 2]

0    rohit.sharma@email.com
1     virat.kohli@email.com
Name: email, dtype: str

In [22]:
df.loc[0]

first                     Rohit
last                     Sharma
email    rohit.sharma@email.com
Name: 0, dtype: str

In [23]:
df.loc[[0,1], 'email']

0    rohit.sharma@email.com
1     virat.kohli@email.com
Name: email, dtype: str

In [24]:
df.loc[[0,1], ['email', 'last']]

                    email    last
0  rohit.sharma@email.com  Sharma
1   virat.kohli@email.com   Kohli

In [28]:
res_df = pd.read_csv('data/survey_results_public.csv')
schema_df = pd.read_csv('data/survey_results_schema.csv')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

/var/folders/y8/svf1rw9x0zs_d6z8j3nzm3sc0000gn/T/ipykernel_51960/3067905798.py:1: DtypeWarning: Columns (0: JobSatPoints_15_TEXT, 1: DatabaseHaveEntry, 2: DevEnvHaveEntry, 3: SOTagsHaveEntry, 4: SOTagsWant Entry, 5: OfficeStackWantEntry, 6: CommPlatformHaveEntr, 7: CommPlatformWantEntr, 8: SO_Actions_15_TEXT, 9: AIAgentOrchestration, 10: AIAgentObsWrite) have mixed types. Specify dtype option on import or set low_memory=False.
  res_df = pd.read_csv('data/survey_results_public.csv')

## Practicing with Real Data
Now let's apply these selection techniques to our Stack Overflow survey dataset.

In [29]:
res_df.shape

(49191, 172)

In [31]:
list(res_df.columns)

['ResponseId',
 'MainBranch',
 'Age',
 'EdLevel',
 'Employment',
 'EmploymentAddl',
 'WorkExp',
 'LearnCodeChoose',
 'LearnCode',
 'LearnCodeAI',
 'AILearnHow',
 'YearsCode',
 'DevType',
 'OrgSize',
 'ICorPM',
 'RemoteWork',
 'PurchaseInfluence',
 'TechEndorseIntro',
 'TechEndorse_1',
 'TechEndorse_2',
 'TechEndorse_3',
 'TechEndorse_4',
 'TechEndorse_5',
 'TechEndorse_6',
 'TechEndorse_7',
 'TechEndorse_8',
 'TechEndorse_9',
 'TechEndorse_13',
 'TechEndorse_13_TEXT',
 'TechOppose_1',
 'TechOppose_2',
 'TechOppose_3',
 'TechOppose_5',
 'TechOppose_7',
 'TechOppose_9',
 'TechOppose_11',
 'TechOppose_13',
 'TechOppose_16',
 'TechOppose_15',
 'TechOppose_15_TEXT',
 'Industry',
 'JobSatPoints_1',
 'JobSatPoints_2',
 'JobSatPoints_3',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'JobSatPoints_13',
 'JobSatPoints_14',
 'JobSatPoints_15',
 'JobSatPoints_16',
 'JobSatPoints_15_TEXT',
 'AIThreat',
 'NewRole',
 'ToolCountWork',
 'ToolCountPersonal',
 'Country',
 'Currency',
 'CompTotal',
 'LanguageChoice',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'DatabaseChoice',
 'DatabaseHaveWorkedWith',
 'DatabaseWantToWorkWith',
 'DatabaseAdmired',
 'DatabaseHaveEntry',
 'DatabaseWantEntry',
 'PlatformChoice',
 'PlatformHaveWorkedWith',
 'PlatformWantToWorkWith',
 'PlatformAdmired',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'WebframeChoice',
 'WebframeHaveWorkedWith',
 'WebframeWantToWorkWith',
 'WebframeAdmired',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'DevEnvsChoice',
 'DevEnvsHaveWorkedWith',
 'DevEnvsWantToWorkWith',
 'DevEnvsAdmired',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'SOTagsHaveWorkedWith',
 'SOTagsWantToWorkWith',
 'SOTagsAdmired',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'OpSysPersonal use',
 'OpSysProfessional use',
 'OfficeStackAsyncHaveWorkedWith',
 'OfficeStackAsyncWantToWorkWith',
 'OfficeStackAsyncAdmired',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'CommPlatformHaveWorkedWith',
 'CommPlatformWantToWorkWith',
 'CommPlatformAdmired',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIModelsChoice',
 'AIModelsHaveWorkedWith',
 'AIModelsWantToWorkWith',
 'AIModelsAdmired',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'SOAccount',
 'SOVisitFreq',
 'SODuration',
 'SOPartFreq',
 'SO_Dev_Content',
 'SO_Actions_1',
 'SO_Actions_16',
 'SO_Actions_3',
 'SO_Actions_4',
 'SO_Actions_5',
 'SO_Actions_6',
 'SO_Actions_9',
 'SO_Actions_7',
 'SO_Actions_10',
 'SO_Actions_15',
 'SO_Actions_15_TEXT',
 'SOComm',
 'SOFriction',
 'AISelect',
 'AISent',
 'AIAcc',
 'AIComplex',
 'AIToolCurrently partially AI',
 "AIToolDon't plan to use AI for this task",
 'AIToolPlan to partially use AI',
 'AIToolPlan to mostly use AI',
 'AIToolCurrently mostly AI',
 'AIFrustration',
 'AIExplain',
 'AIAgents',
 'AIAgentChange',
 'AIAgent_Uses',
 'AgentUsesGeneral',
 'AIAgentImpactSomewhat agree',
 'AIAgentImpactNeutral',
 'AIAgentImpactSomewhat disagree',
 'AIAgentImpactStrongly agree',
 'AIAgentImpactStrongly disagree',
 'AIAgentChallengesNeutral',
 'AIAgentChallengesSomewhat disagree',
 'AIAgentChallengesStrongly agree',
 'AIAgentChallengesSomewhat agree',
 'AIAgentChallengesStrongly disagree',
 'AIAgentKnowledge',
 'AIAgentKnowWrite',
 'AIAgentOrchestration',
 'AIAgentOrchWrite',
 'AIAgentObserveSecure',
 'AIAgentObsWrite',
 'AIAgentExternal',
 'AIAgentExtWrite',
 'AIHuman',
 'AIOpen',
 'ConvertedCompYearly',
 'JobSat']

In [32]:
for col in res_df.columns:
    print(col)

ResponseId
MainBranch
Age
EdLevel
Employment
EmploymentAddl
WorkExp
LearnCodeChoose
LearnCode
LearnCodeAI
AILearnHow
YearsCode
DevType
OrgSize
ICorPM
RemoteWork
PurchaseInfluence
TechEndorseIntro
TechEndorse_1
TechEndorse_2
TechEndorse_3
TechEndorse_4
TechEndorse_5
TechEndorse_6
TechEndorse_7
TechEndorse_8
TechEndorse_9
TechEndorse_13
TechEndorse_13_TEXT
TechOppose_1
TechOppose_2
TechOppose_3
TechOppose_5
TechOppose_7
TechOppose_9
TechOppose_11
TechOppose_13
TechOppose_16
TechOppose_15
TechOppose_15_TEXT
Industry
JobSatPoints_1
JobSatPoints_2
JobSatPoints_3
JobSatPoints_4
JobSatPoints_5
JobSatPoints_6
JobSatPoints_7
JobSatPoints_8
JobSatPoints_9
JobSatPoints_10
JobSatPoints_11
JobSatPoints_13
JobSatPoints_14
JobSatPoints_15
JobSatPoints_16
JobSatPoints_15_TEXT
AIThreat
NewRole
ToolCountWork
ToolCountPersonal
Country
Currency
CompTotal
LanguageChoice
LanguageHaveWorkedWith
LanguageWantToWorkWith
LanguageAdmired
LanguagesHaveEntry
LanguagesWantEntry
DatabaseChoice
DatabaseHaveWorkedWith
DatabaseWantToWorkWith
DatabaseAdmired
DatabaseHaveEntry
DatabaseWantEntry
PlatformChoice
PlatformHaveWorkedWith
PlatformWantToWorkWith
PlatformAdmired
PlatformHaveEntry
PlatformWantEntry
WebframeChoice
WebframeHaveWorkedWith
WebframeWantToWorkWith
WebframeAdmired
WebframeHaveEntry
WebframeWantEntry
DevEnvsChoice
DevEnvsHaveWorkedWith
DevEnvsWantToWorkWith
DevEnvsAdmired
DevEnvHaveEntry
DevEnvWantEntry
SOTagsHaveWorkedWith
SOTagsWantToWorkWith
SOTagsAdmired
SOTagsHaveEntry
SOTagsWant Entry
OpSysPersonal use
OpSysProfessional use
OfficeStackAsyncHaveWorkedWith
OfficeStackAsyncWantToWorkWith
OfficeStackAsyncAdmired
OfficeStackHaveEntry
OfficeStackWantEntry
CommPlatformHaveWorkedWith
CommPlatformWantToWorkWith
CommPlatformAdmired
CommPlatformHaveEntr
CommPlatformWantEntr
AIModelsChoice
AIModelsHaveWorkedWith
AIModelsWantToWorkWith
AIModelsAdmired
AIModelsHaveEntry
AIModelsWantEntry
SOAccount
SOVisitFreq
SODuration
SOPartFreq
SO_Dev_Content
SO_Actions_1
SO_Actions_16
SO_Actions_3
SO_Actions_4
SO_Actions_5
SO_Actions_6
SO_Actions_9
SO_Actions_7
SO_Actions_10
SO_Actions_15
SO_Actions_15_TEXT
SOComm
SOFriction
AISelect
AISent
AIAcc
AIComplex
AIToolCurrently partially AI
AIToolDon't plan to use AI for this task
AIToolPlan to partially use AI
AIToolPlan to mostly use AI
AIToolCurrently mostly AI
AIFrustration
AIExplain
AIAgents
AIAgentChange
AIAgent_Uses
AgentUsesGeneral
AIAgentImpactSomewhat agree
AIAgentImpactNeutral
AIAgentImpactSomewhat disagree
AIAgentImpactStrongly agree
AIAgentImpactStrongly disagree
AIAgentChallengesNeutral
AIAgentChallengesSomewhat disagree
AIAgentChallengesStrongly agree
AIAgentChallengesSomewhat agree
AIAgentChallengesStrongly disagree
AIAgentKnowledge
AIAgentKnowWrite
AIAgentOrchestration
AIAgentOrchWrite
AIAgentObserveSecure
AIAgentObsWrite
AIAgentExternal
AIAgentExtWrite
AIHuman
AIOpen
ConvertedCompYearly
JobSat

In [34]:
res_df['AIThreat']

0        I'm not sure
1        I'm not sure
2                  No
3                  No
4                  No
             ...
49186             NaN
49187             NaN
49188              No
49189             NaN
49190             NaN
Name: AIThreat, Length: 49191, dtype: str

In [35]:
res_df['AIThreat'].value_counts()

AIThreat
No              22958
I'm not sure     7700
Yes              5420
Name: count, dtype: int64

In [36]:
res_df.loc[0]

ResponseId                                                           1
MainBranch                              I am a developer by profession
Age                                                    25-34 years old
EdLevel                Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
Employment                                                    Employed
                                            ...
AIAgentExtWrite                                                    NaN
AIHuman                                When I don’t trust AI’s answers
AIOpen                           Troubleshooting, profiling, debugging
ConvertedCompYearly                                            61256.0
JobSat                                                            10.0
Name: 0, Length: 172, dtype: object

In [37]:
res_df.loc[[0, 1, 2], 'AIThreat']

0    I'm not sure
1    I'm not sure
2              No
Name: AIThreat, dtype: str

In [38]:
res_df.loc[0:2]

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0

In [40]:
res_df.loc[0, 'AIThreat']

"I'm not sure"

In [41]:
res_df.loc[0:2, 'AIThreat']

0    I'm not sure
1    I'm not sure
2              No
Name: AIThreat, dtype: str

In [42]:
res_df.loc[0:2, 'AIThreat':'Country']

,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country
0,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine
1,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands
2,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine

### Slicing with loc
With `loc`, you can even slice columns. Note that unlike standard Python slicing, the end point in pandas `loc` is **inclusive**.