In [1]:
import pandas as pd

In [3]:
people = {
    "first": ["Rohit", "Virat", "Jasprit", "Shubman", "Hardik", "Rishabh", "Suryakumar", "Ravindra", "Kuldeep", "Arshdeep", "Axar"],
    "last": ["Sharma", "Kohli", "Bumrah", "Gill", "Pandya", "Pant", "Yadav", "Jadeja", "Yadav", "Singh", "Patel"],
    "email": [
        "rohit.sharma@email.com", 
        "virat.kohli@email.com", 
        "jasprit.bumrah@email.com", 
        "shubman.gill@email.com", 
        "hardik.pandya@email.com", 
        "rishabh.pant@email.com", 
        "suryakumar.yadav@email.com", 
        "ravindra.jadeja@email.com", 
        "kuldeep.yadav@email.com", 
        "arshdeep.singh@email.com", 
        "axar.patel@email.com"
    ]
}

In [4]:
df = pd.DataFrame(people)

In [5]:
df

         first    last                       email
0        Rohit  Sharma      rohit.sharma@email.com
1        Virat   Kohli       virat.kohli@email.com
2      Jasprit  Bumrah    jasprit.bumrah@email.com
3      Shubman    Gill      shubman.gill@email.com
4       Hardik  Pandya     hardik.pandya@email.com
5      Rishabh    Pant      rishabh.pant@email.com
6   Suryakumar   Yadav  suryakumar.yadav@email.com
7     Ravindra  Jadeja   ravindra.jadeja@email.com
8      Kuldeep   Yadav     kuldeep.yadav@email.com
9     Arshdeep   Singh    arshdeep.singh@email.com
10        Axar   Patel        axar.patel@email.com

In [6]:
df['last'] == 'Doe'

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
Name: last, dtype: bool

In [7]:
filt = (df['last'] == 'Doe')

In [8]:
df[filt]

Empty DataFrame
Columns: [first, last, email]
Index: []

In [9]:
df[df['last'] == 'Yadav']

        first   last                       email
6  Suryakumar  Yadav  suryakumar.yadav@email.com
8     Kuldeep  Yadav     kuldeep.yadav@email.com

In [10]:
df.loc[filt]

Empty DataFrame
Columns: [first, last, email]
Index: []

In [11]:
df.loc[filt, 'email']

Series([], Name: email, dtype: str)

In [12]:
filt = (df['last'] == 'Yadav') & (df['first'] == 'Suryakumar')

In [13]:
df.loc[filt, 'email']

6    suryakumar.yadav@email.com
Name: email, dtype: str

In [14]:
filt = (df['last'] == 'Sharma') | (df['first'] == 'Rohit')

In [15]:
df.loc[filt, 'email']

0    rohit.sharma@email.com
Name: email, dtype: str

In [16]:
df.loc[~filt, 'email']

1          virat.kohli@email.com
2       jasprit.bumrah@email.com
3         shubman.gill@email.com
4        hardik.pandya@email.com
5         rishabh.pant@email.com
6     suryakumar.yadav@email.com
7      ravindra.jadeja@email.com
8        kuldeep.yadav@email.com
9       arshdeep.singh@email.com
10          axar.patel@email.com
Name: email, dtype: str

In [18]:
df = pd.read_csv('data/survey_results_public.csv', index_col='ResponseId')
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='qname')

/var/folders/y8/svf1rw9x0zs_d6z8j3nzm3sc0000gn/T/ipykernel_59717/3211394593.py:1: DtypeWarning: Columns (0: AIThreat, 1: DatabaseWantEntry, 2: DevEnvWantEntry, 3: SOTagsWant Entry, 4: OpSysPersonal use, 5: CommPlatformHaveWorkedWith, 6: CommPlatformWantEntr, 7: AIModelsChoice, 8: SOComm, 9: AIAgentOrchWrite, 10: AIAgentExternal) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/survey_results_public.csv', index_col='ResponseId')

In [19]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [20]:
df.head(2)

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,...,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,...,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,...,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0

In [21]:
high_salary = (df['ConvertedCompYearly'] > 70000)

In [22]:
df.loc[high_salary]

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,...,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,...,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,20.0,"Developer, back-end",NaN,NaN,NaN,"Yes, I influenced the purchase of a substantia...",Work,12.0,5.0,4.0,6.0,2.0,10.0,3.0,7.0,8.0,14.0,NaN,12.0,5.0,13.0,10.0,9.0,1.0,4.0,6.0,2.0,15.0,NaN,Fintech,4.0,3.0,...,11.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Indifferent,Somewhat distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Predictive analytics,Deployment and monitoring,Project planning;Debugging or fixing code;Comm...,Testing code;Learning new concepts or technolo...,"AI solutions that are almost right, but not quite",No it isnt,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,NaN,AI agents have improved the quality of my code...,AI agents have helped me automate repetitive t...,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0
8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Blogs or p...,30.0,"Architect, software or solutions",Less than 20 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Personal Project,12.0,2.0,1.0,10.0,4.0,5.0,8.0,6.0,7.0,14.0,NaN,14.0,3.0,4.0,9.0,1.0,5.0,2.0,11.0,12.0,15.0,NaN,Software Development,7.0,9.0,...,11.0,15.0,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,Writing code;Documenting code,NaN,Project planning;Debugging or fixing code;Depl...,Learning about a codebase;Testing code;Committ...,Search for answers;Learning new concepts or te...,"AI solutions that are almost right, but not qu...",Yes,"No, but I plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have concerns about the security and privacy...,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I wan...,"Innovation, system design",72000.0,6.0
23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training,11.0,"Developer, full-stack",100 to 499 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,9.0,10.0,1.0,11.0,4.0,2.0,5.0,14.0,NaN,14.0,2.0,8.0,12.0,4.0,1.0,13.0,10.0,3.0,15.0,NaN,Fintech,3.0,2.0,...,9.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Unfavorable,Somewhat distrust,Bad at handling complex tasks,Writing code,Learning about a codebase;Project planning;Doc...,Debugging or fixing code;Creating or maintaini...,Predictive analytics,NaN,"AI solutions that are almost right, but not qu...","No. I find it to be useless, unless I'm starti...","No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0
26,I am a developer by profession,55-64 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,37.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Blogs or p...,41.0,"Developer, full-stack",NaN,NaN,NaN,"Yes, I influenced the purchase of a substantia...",Personal Project,7.0,5.0,4.0,2.0,1.0,8.0,3.0,6.0,13.0,14.0,NaN,11.0,2.0,8.0,5.0,6.0,4.0,1.0,3.0,9.0,15.0,NaN,Software Development,2.0,1.0,...,13.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,"AI solutions that are almost right, but not quite",Sometimes. But rarely for important profession...,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering;Marketing,Integration with external agents and APIs,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,NaN,AI agents have helped me automate repetitive t...,NaN,Integrating AI agents with my existing tools a...,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Replit,NaN,When I don’t trust AI’s answers;When I want to...,Choosing the best solutions. Converting user r...,108913.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49067,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",19.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,22.0,"Developer, full-stack","5,000 to 9,999 employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,1.0,6.0,3.0,7.0,5.0,2.0,8.0,9.0,4.0,10.0,NaN,6.0,9.0,7.0,2.0,1.0,3.0,8.0,5.0,4.0,10.0,NaN,Retail and Consumer Services,13.0,6.0,...,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Favorable,Highly distrust,"Good, but not great at handling complex tasks",Debugging or fixing code;Testing code;Creating...,Predictive analytics,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Documen...,NaN,"AI solutions that are almost right, but not qu...","No, I don't write enough new code at the momen...","Yes, I use AI agents at work monthly or infreq...","Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138470.0,6.0
49076,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",NaN,10.0,"Developer, full-stack","1,000 to 4,999 employees",Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,9.0,1.0,6.0,3.0,2.0,8.0,7.0,4.0,5.0,10.0,NaN,5.0,2.0,9.0,8.0,1.0,7.0,4.0,3.0,6.0,10.0,NaN,"Transportation, or Supply Chain",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools weekly",Favorable,Somewhat distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Debuggi...,NaN,Project planning;Documenting code;Testing code...,NaN,NaN,"AI solutions that are almost right, but not qu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82366.0,2.0
49084,"I am not primarily a developer, but I write co...",35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,22.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",NaN,5.0,DevOps engineer or professional,"10,000 or more employees",Individual contributor,Remote,No,Work,8.0,4.0,7.0,9.0,1.0,6.0,2.0,5.0,3.0,10.0,NaN,6.0,8.0,5.0,9.0,1.0,3.0,2.0,7.0,4.0,10.0,NaN,Retail and Consumer Services,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Favorable,Highly trust,Bad at handling complex tasks,NaN,NaN,NaN,NaN,NaN,Debugging AI-generated code is more time-consu...,NaN,"No, but I plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188000.0,NaN
49085,"I am not primarily a developer, but I write co...",55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Not employed,None of the above,46.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I didn't spend time learning in the past year",NaN,8.0,"Developer, QA or test",NaN,NaN,NaN,NaN,Personal Project,9.0,3.0,6.0,4.0,5.0,2.0,8.0,7.0,1.0,10.0,NaN,7.0,5.0,9.0,8.0,3.0,1.0,6.0,2.0,4.0,10.0,NaN,NaN,NaN,NaN,...,8.0,10.0,NaN,"No, not really","Rarely, almost never","No, but I plan to soon",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Search for answers;Generating content or synth...,Project planning;Deployment and monitoring;Pre...,Learning about a codebase;Writing code;Documen...,NaN,NaN,I haven’t encountered any problems,It is not.,"No, but I plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119000.0,NaN
49089,I work with developers or my work supports dev...,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,15.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Blogs or p...,10.0,Engineering manager,100 to 499 employees,People manager,Remote,"Yes, I influenced the purchase of a tool that ...",Work,5.0,4.0,3.0,7.0,1.0,9.0,8.0,6.0,2.0,10.0,NaN,6.0,4.0,9.0,5.0,3.0,2.0,7.0,1.0,8.0,10.0,NaN,Software Development,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,280000.0,NaN

In [24]:
df.loc[high_salary, ['Country', 'EdLevel', 'ConvertedCompYearly']]

,Country,EdLevel,ConvertedCompYearly
ResponseId,,,
2,Netherlands,"Associate degree (A.A., A.S., etc.)",104413.0
6,Ukraine,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",120000.0
8,Ukraine,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",72000.0
23,United States of America,Some college/university study without earning ...,87500.0
26,United Kingdom of Great Britain and Northern I...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",108913.0
...,...,...,...
49067,Australia,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",138470.0
49076,United Kingdom of Great Britain and Northern I...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",82366.0
49084,United States of America,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",188000.0
49085,United States of America,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",119000.0
49089,United States of America,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",280000.0

In [25]:
countries = ['United States', 'India', 'United Kingdom', 'Germany', 'Canada']

In [26]:
filt = df['Country'].isin(countries)

In [27]:
df.loc[filt, 'Country']

ResponseId
14         India
16         India
19       Germany
36       Germany
47         India
          ...
49155      India
49156      India
49176    Germany
49179    Germany
49181     Canada
Name: Country, Length: 6877, dtype: str

In [28]:
df['EdLevel']

ResponseId
1          Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
2                      Associate degree (A.A., A.S., etc.)
3             Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4             Bachelor’s degree (B.A., B.S., B.Eng., etc.)
5          Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
                               ...
49187         Bachelor’s degree (B.A., B.S., B.Eng., etc.)
49188    Some college/university study without earning ...
49189      Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
49190       Professional degree (JD, MD, Ph.D, Ed.D, etc.)
49191    Some college/university study without earning ...
Name: EdLevel, Length: 49191, dtype: str

In [30]:
filt = df['EdLevel'].str.contains('Master', na=False)

In [31]:
filt

ResponseId
1         True
2        False
3        False
4        False
5         True
         ...
49187    False
49188    False
49189     True
49190    False
49191    False
Name: EdLevel, Length: 49191, dtype: bool

In [32]:
df.loc[filt, 'EdLevel']

ResponseId
1        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
5        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
6        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
10       Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
11       Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
                              ...
49162    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
49167    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
49176    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
49184    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
49189    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
Name: EdLevel, Length: 12589, dtype: str